=== bkopfdev/assignment-1--principles-of-databases--cs-365--fall-2025/xml/student.dtd
<!-- student-log (the root element) can contain one or more student elements-->
<!ELEMENT student-log (student)+>

<!-- A student element MUST contain a first name, last name, full contact info and academic info, aside from their graduation date and minor. A student does not need a middle-name, preferred-name, minor, or graduation-date by design. Not all students have a middle or preferred name, not everyone gets a minor, and not everyone knows when they will graduate -->
<!ELEMENT student (first-name, middle-name?, last-name, preferred-name?, contact-info, academic-info)>
<!ELEMENT first-name (#PCDATA)>
<!ELEMENT middle-name (#PCDATA)>
<!ELEMENT last-name (#PCDATA)>
<!ELEMENT preferred-name (#PCDATA)>

<!-- id CDATA is a required field used to differentiate students from eachother. It's shown in the frontend through the css, using an [attr] field -->
<!ATTLIST student
          id CDATA #REQUIRED>

<!-- All the information related to contact-info -->
<!ELEMENT contact-info (email, phone)>
<!ELEMENT email (#PCDATA)>
<!ELEMENT phone (#PCDATA)>

<!-- All the information related to academic-info -->
<!ELEMENT academic-info (status-year,gpa,major,minor?,status-enrollment,advisor,date-initial-enrollment,graduation-date?)>
<!ELEMENT status-year (#PCDATA)>
<!ELEMENT gpa (#PCDATA)>
<!ELEMENT major (#PCDATA)>
<!ELEMENT minor (#PCDATA)>
<!ELEMENT status-enrollment (#PCDATA)>
<!ELEMENT advisor (#PCDATA)>
<!ELEMENT date-initial-enrollment (#PCDATA)>
<!ELEMENT graduation-date (#PCDATA)>

=== bkopfdev/assignment-1--principles-of-databases--cs-365--fall-2025/xml/index.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE student-log SYSTEM "student.dtd">

<!-- I utilized the attr function in the DTD with the "id" attribute for each student, along with the enrollment and year status (because its an enum). But, other than that, I decided to simply fill in the content for each, much like the music-library example I referenced from the repo-->
<student-log>
  <student id = "1234567">
    <first-name>Gordon</first-name>
    <middle-name>Matthew</middle-name>
    <last-name>Sumner</last-name>
    <preferred-name>Sting</preferred-name>
    <contact-info>
      <email>sting@thepolice.com</email>
      <phone>212.123.4567</phone>
    </contact-info>
    <status enrollment="full-time" year="first-year"></status>
    <academic-info>
      <gpa>4.0</gpa>
      <major>Music</major>
      <minor>English</minor>
      <advisor>Andy Summers</advisor>
      <date-initial-enrollment>08-25-1969</date-initial-enrollment>
      <graduation-date>05-01-1973</graduation-date>
    </academic-info>
  </student>

  <student id = "4567890">
    <first-name>Kim</first-name>
    <middle-name></middle-name>
    <last-name>Thayil</last-name>
    <preferred-name></preferred-name>
    <contact-info>
      <email>kim@soundgarden.com</email>
      <phone>206.123.4567</phone>
    </contact-info>
    <status enrollment="full-time" year="second-year"></status>
    <academic-info>
      <gpa>3.0</gpa>
      <major>Philosophy</major>
      <minor>Music</minor>
      <advisor>Chris Cornell</advisor>
      <date-initial-enrollment>08-25-1978</date-initial-enrollment>
      <graduation-date>05-01-1982</graduation-date>
    </academic-info>
  </student>

  <student id = "8302438">
    <first-name>Saul</first-name>
    <middle-name></middle-name>
    <last-name>Hudson</last-name>
    <preferred-name>Slash</preferred-name>
    <contact-info>
      <email>slash@gnr.com</email>
      <phone>213.456.8392</phone>
    </contact-info>
    <status enrollment="part-time" year="fourth-year"></status>
    <academic-info>
      <gpa>2.0</gpa>
      <major>Music</major>
      <minor>Criminal Justice</minor>
      <advisor>Axl Rose</advisor>
      <date-initial-enrollment>08-25-1983</date-initial-enrollment>
      <graduation-date>05-01-1987</graduation-date>
    </academic-info>
  </student>

  <student id = "2983928">
    <first-name>Emily</first-name>
    <middle-name></middle-name>
    <last-name>Kokal</last-name>
    <preferred-name></preferred-name>
    <contact-info>
      <email>emily@warpaint.com</email>
      <phone>213.123.7654</phone>
    </contact-info>
    <status enrollment="full-time" year="third-year"></status>
    <academic-info>
      <gpa>3.8</gpa>
      <major>Political Science</major>
      <minor>Law</minor>
      <advisor>Jenny Lee Lindberg</advisor>
      <date-initial-enrollment>08-25-1998</date-initial-enrollment>
      <graduation-date>05-01-2002</graduation-date>
    </academic-info>
  </student>

  <student id = "7645726">
    <first-name>Mike</first-name>
    <middle-name></middle-name>
    <last-name>Inez</last-name>
    <preferred-name></preferred-name>
    <contact-info>
      <email>mike@aic.com</email>
      <phone>213.444.3323</phone>
    </contact-info>
    <status enrollment="full-time" year="second-year"></status>
    <academic-info>
      <gpa>4.0</gpa>
      <major>Business Management</major>
      <minor>Math</minor>
      <advisor>Jerry Cantrell</advisor>
      <date-initial-enrollment>08-25-1984</date-initial-enrollment>
      <graduation-date>05-01-1988</graduation-date>
    </academic-info>
  </student>

</student-log>
